//! The `Hasher` trait and the raw/normalized content-hash helpers Båge uses
//! for drift discipline (SPEC §4.3). `raw_hash` gates byte-offset validity
//! against the live file; `norm_hash` classifies whitespace-only drift.
//!
//! [`XxHasher`] is the canonical implementation, matching Hylla's content
//! hash; [`FnvHasher`] is a dependency-free fallback. The two-hash semantics
//! are engine-independent, so the drift logic is unaffected by which `Hasher`
//! is used.

use xxhash_rust::xxh64::xxh64;

use crate::normalize::normalize;

/// Computes a stable hex digest of a byte slice. Implementations must be
/// deterministic and free of hidden state so equal inputs always yield equal
/// digests.
pub trait Hasher: Send + Sync {
    /// Returns the lowercase hex-encoded digest of `b`.
    fn sum(&self, b: &[u8]) -> String;
}

/// The canonical content hash shared with Hylla: xxHash64, formatted as the
/// 16-character, zero-padded, lowercase hex of the 64-bit sum, so Båge (Go
/// and Rust) and Hylla produce byte-identical digests for identical inputs.
/// This fixed format IS the cross-system contract: any change to the width or
/// encoding here must be mirrored on the Hylla side.
#[derive(Debug, Clone, Copy, Default)]
pub struct XxHasher;

impl Hasher for XxHasher {
    fn sum(&self, b: &[u8]) -> String {
        format!("{:016x}", xxh64(b, 0))
    }
}

/// Dependency-free fallback implementing `Hasher` with FNV-1a (64-bit),
/// hex-encoded. [`XxHasher`] is the canonical hasher shared with Hylla.
#[derive(Debug, Clone, Copy, Default)]
pub struct FnvHasher;

impl Hasher for FnvHasher {
    fn sum(&self, b: &[u8]) -> String {
        const OFFSET_BASIS: u64 = 0xcbf29ce484222325;
        const PRIME: u64 = 0x100000001b3;
        let mut h = OFFSET_BASIS;
        for &c in b {
            h ^= u64::from(c);
            h = h.wrapping_mul(PRIME);
        }
        format!("{h:016x}")
    }
}

/// Returns the digest of `raw` exactly as given, gating byte-offset validity:
/// a byte range is trustworthy only while the live file's raw hash is
/// unchanged.
pub fn raw_hash(h: &dyn Hasher, raw: &[u8]) -> String {
    h.sum(raw)
}

/// Returns the digest of `raw` after normalization, classifying
/// whitespace-only drift: when the raw hash differs but the normalized hash
/// matches, the change is whitespace-only and the range can be re-grounded
/// rather than rejected.
pub fn norm_hash(h: &dyn Hasher, raw: &[u8]) -> String {
    h.sum(&normalize(raw))
}

#[cfg(test)]
mod tests {
    use super::*;

    // Parity vectors generated by the Go bage binary (bin/bage create),
    // pinning the cross-system xxHash64 {:016x} contract.
    #[test]
    fn xxhasher_matches_go_parity_vectors() {
        let h = XxHasher;
        assert_eq!(h.sum(b""), "ef46db3751d8e999");
        assert_eq!(h.sum(b"hello world\n"), "5215e13b207d6d8c");
        let v4 = b"a \t\r\nb\r\n\xEF\xBB\xBFc  \n";
        assert_eq!(raw_hash(&h, v4), "ea797be75ac87c05");
        assert_eq!(norm_hash(&h, v4), "eff696b098387009");
    }

    #[test]
    fn digest_is_16_lowercase_hex() {
        for input in [&b""[..], b"a", b"\x00\xff", b"longer input with spaces"] {
            for hasher in [&XxHasher as &dyn Hasher, &FnvHasher] {
                let d = hasher.sum(input);
                assert_eq!(d.len(), 16, "digest {d:?}");
                assert!(d.bytes().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
            }
        }
    }

    #[test]
    fn norm_hash_ignores_whitespace_only_change() {
        let h = XxHasher;
        let a = b"fn main() {}\n";
        let b = b"fn main() {}   \r\n";
        assert_ne!(raw_hash(&h, a), raw_hash(&h, b));
        assert_eq!(norm_hash(&h, a), norm_hash(&h, b));
    }
}
