//! Shared content-normalization rule used to compute Båge's normalized
//! content hash. The rule is byte-identical with the Go implementation and
//! Hylla's, so all three systems agree on whitespace-only drift
//! classification.
//!
//! The rule, in order:
//!
//! 1. normalize line endings to LF by dropping every carriage return (`\r`);
//! 2. strip trailing horizontal whitespace (`[ \t\r]`) immediately before
//!    each LF and at end-of-input;
//! 3. strip ALL consecutive leading UTF-8 BOMs (`EF BB BF`) — LAST.
//!
//! Interior whitespace (including tabs) is preserved byte-for-byte. The ORDER
//! is load-bearing for idempotency (and region_hash stability across
//! systems): BOM stripping runs last, on the CR-free output, so a `\r`
//! embedded in a BOM byte run cannot re-form a leading BOM after the strip;
//! and ALL leading BOMs are stripped, not just one. Both are fuzz-discovered
//! invariants — the Go side and Hylla MUST match.

/// The UTF-8 byte-order-mark sequence stripped from the start of input.
const BOM: [u8; 3] = [0xEF, 0xBB, 0xBF];

/// Applies Båge's canonical content-normalization rule, returning a newly
/// allocated buffer; the input is never mutated. Pure function, no I/O.
pub fn normalize(b: &[u8]) -> Vec<u8> {
    // Steps 1 & 2: drop all \r, and buffer any run of horizontal whitespace
    // until a non-whitespace, non-LF byte proves it was interior. Buffered
    // whitespace before an LF or at EOF is discarded.
    let mut out: Vec<u8> = Vec::with_capacity(b.len());
    let mut pending: Vec<u8> = Vec::with_capacity(16);
    for &c in b {
        match c {
            // Dropped entirely; also counts toward trailing-ws stripping.
            b'\r' => {}
            b' ' | b'\t' => pending.push(c),
            b'\n' => {
                // Trailing horizontal whitespace before the newline is discarded.
                pending.clear();
                out.push(b'\n');
            }
            _ => {
                // Interior whitespace is real: flush it verbatim, then the byte.
                out.append(&mut pending);
                out.push(c);
            }
        }
    }
    // Any whitespace pending at EOF is trailing and discarded.

    // Step 3: strip every consecutive leading UTF-8 BOM — done LAST, after \r
    // removal, on purpose. A \r embedded inside the BOM byte run (e.g. EF BB
    // \r BF) would otherwise be removed by the loop above and re-form a
    // leading BOM that an earlier strip had already walked past, breaking
    // idempotency. Doing it on the CR-free output guarantees the result never
    // begins with a BOM, so re-normalizing is a fixpoint.
    let mut start = 0;
    while out[start..].starts_with(&BOM) {
        start += BOM.len();
    }
    out.drain(..start);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_cases() {
        let cases: &[(&str, &[u8], &[u8])] = &[
            ("empty", b"", b""),
            ("plain", b"hello\n", b"hello\n"),
            ("crlf to lf", b"a\r\nb\r\n", b"a\nb\n"),
            ("bare cr dropped", b"a\rb", b"ab"),
            ("trailing spaces before lf", b"a  \nb\t\n", b"a\nb\n"),
            ("trailing ws at eof", b"a  ", b"a"),
            ("interior ws preserved", b"a  b\tc\n", b"a  b\tc\n"),
            ("single leading bom", b"\xEF\xBB\xBFa\n", b"a\n"),
            ("multiple leading boms", b"\xEF\xBB\xBF\xEF\xBB\xBFa\n", b"a\n"),
            ("interior bom preserved", b"a\n\xEF\xBB\xBFb\n", b"a\n\xEF\xBB\xBFb\n"),
            // A \r-split BOM collapses under \r-removal, then strips (the
            // fuzz-discovered ordering invariant).
            ("cr-split leading bom", b"\xEF\xBB\r\xBFa\n", b"a\n"),
            ("only whitespace", b" \t \r", b""),
            // Parity vector v4 (generated by the Go bage binary).
            (
                "go parity v4",
                b"a \t\r\nb\r\n\xEF\xBB\xBFc  \n",
                b"a\nb\n\xEF\xBB\xBFc\n",
            ),
        ];
        for (name, input, want) in cases {
            assert_eq!(&normalize(input), want, "case {name}");
        }
    }

    #[test]
    fn normalize_idempotent() {
        // Deterministic pseudo-random byte strings biased toward the bytes
        // the rule cares about, mirroring the Go fuzz invariant.
        let alphabet: &[u8] = b"\r\n \t\xEF\xBB\xBFabc";
        let mut state: u64 = 0x9E3779B97F4A7C15;
        for len in 0..64 {
            for _ in 0..256 {
                let mut input = Vec::with_capacity(len);
                for _ in 0..len {
                    state = state
                        .wrapping_mul(6364136223846793005)
                        .wrapping_add(1442695040888963407);
                    input.push(alphabet[(state >> 33) as usize % alphabet.len()]);
                }
                let once = normalize(&input);
                let twice = normalize(&once);
                assert_eq!(once, twice, "not idempotent for {input:?}");
            }
        }
    }

    #[test]
    fn normalize_never_starts_with_bom() {
        let out = normalize(b"\xEF\xBB\xBF\xEF\xBB\r\xBF\xEF\xBB\xBFx");
        assert!(!out.starts_with(&BOM));
        assert_eq!(out, b"x");
    }
}
